### ISSUE TITLE
Incorrect file path in REPL on Windows

### ISSUE THREAD

**Issue by jesnor** [zjhmale/vscode-idris#65]
When I run the "Start or Refresh REPL" command it tries to load an incorrect file path:

Idris> :l c:codeIdrisTesttest.idr
Can't find import c:codeIdrisTesttest.idr

The correct path is "c:\code\IdrisTest\test.idr". I'm running on Windows 7.

**Comment by zjhmale** [comment]
Hi @jesnor it seems to be an upstream bug with VSCode itself because the VSCode API does not kindly give back the correct file path on Windows 7 machine.

This extension can greatly work as expected on Windows 10 I believe.

Also highly recommend you to install [.NET 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42643) which mentioned [here](https://code.visualstudio.com/docs/setup/windows)

**Comment by zjhmale** [comment]
Hi @jesnor, do you work it out with this issue? If you still get trouble with this, I will try to fix it if I can kindly get a windows7 machine these days.

**Comment by zjhmale** [comment]
Hi @jesnor, I just got a windows 7 virtual machine installed and it seems everything works fine for me, please make sure the .NET 4.5.2 is already installed on your local machine.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/25302503/db640728-2771-11e7-93c1-e4faf045fce0.gif)

**Comment by be5invis** [comment]
```js
 if (innerCompilerOptions.src && uri.includes(innerCompilerOptions.src)) {
    let [path, module] = uri.split(innerCompilerOptions.src)
    let moduleParts = module.split("/")
    moduleParts.shift()
    let moduleStr = moduleParts.join("/")

    term.sendText(`:cd ${path + innerCompilerOptions.src}`)
    term.sendText(`:l ${moduleStr}`)
    term.show()
  }
```
This is causing it. Change `"/"` to `path.sep`.

**Comment by zjhmale** [comment]
Duplicated with #83
