### ISSUE TITLE
Can't type check any code

### ISSUE THREAD

**Issue by karljs** [zjhmale/vscode-idris#9]
First of all, thanks for working on this extension.  I'm just experimenting with VS Code and was happy to see some Idris support.

Unfortunately, I haven't been able to get much of anything working.  After installing the extension, I opened an existing project of mine and tried to type check it.  When I execute the type checking function, however, absolutely no output is shown.  I added deliberate type errors and still did not see any output.

Unable to debug this, I created an idris file with the following contents:

```
module Junk

data Test
```

When I try to get your extension to type check this code, I get an error popup reading `Running the contributed command:'idris.typecheck' failed` with no further information.  This is more than I get for my larger file, but I'm still not sure what I'm doing wrong.

Any advice would be greatly appreciated.  Idris is on my $PATH installed on OSX via homebrew.

**Comment by zjhmale** [comment]
Hi @karljs, sorry for the delay, I was too much busy these days 😅 

So what exactly the version of Idris are you working with?

**Comment by karljs** [comment]
@zjhmale Thanks for the response.  I'm using Idris installed via Homebrew (currently v0.99 as well) on the exact same version of OSX as you.

I haven't configured VS Code in any way at all, so perhaps there's something I need to do there to make sure it has the correct $PATH or something similar.  I tried a quick search on that topic but without much success.

I will try removing all VS Code preferences and reinstalling the plugin and report back.

**Comment by karljs** [comment]
Deleting all preferences in `~/Library/Application Support` and `~/.vscode` and reinstalling the extension made a little bit of progress.  I now get consistent results in all Idris files.  The problem remains however, that the result is always the same error message about the contributed command failing to run.

**Comment by karljs** [comment]
A little more information (sorry for the many comments):
I get different behavior depending on the current directory of the editor.  If I open a directory with an `ipkg` file and a source file inside a `src` directory, things do not work at all.  If I open the file directly instead of the outer directory, things sort of work but I get the error message.

**Comment by zjhmale** [comment]
Hi @karljs, thanks for your comments :) But currently I have no ideas about what really happened on your side, so do you mind giving me the Idris repo which you are currently working with? Maybe this issue is project-sensitive, so maybe I can work it out, thanks!

**Comment by karljs** [comment]
@zjhmale Sorry for the slow response.  I can give you my Idris code if you like, but ultimately it doesn't work for me with any file, even just a simple one line file with `module Foo` and nothing else.

Do you have any advice for getting more information about what's happening?  Does VS Code have a debug mode or something?  The "debug console" does not seem to be helpful.  My knowledge of VS Code is severely limiting here.  I can click on the little error icon in the bottom left, but it shows "no problems".  I've attached a screenshot, although I doubt it will be helpful.

![screen shot 2017-03-01 at 11 12 05](https://cloud.githubusercontent.com/assets/317063/23476539/f01b1786-fe6f-11e6-813b-ff3aaad6bccc.png)

**Comment by zjhmale** [comment]
Hi @karljs, sorry I still have no idea about your problem there, how about a face to face debugging on skype 😄 Please send me your skype id if you don't mind, cause I have multiple accounts so it is more convenient for me to send the request 😄

**Comment by zjhmale** [comment]
Hi, @karljs, any progress about this? Maybe we can do some diagnosis here:

* can you run `idris --ide-mode` on your command line and see whether everything work as expected?

![image](https://cloud.githubusercontent.com/assets/6234553/23912683/6ece2b6c-091b-11e7-8837-f51a2ee2ca57.png)

* I just want to make sure you are working with a standard Idris project (a Idris project with `src` direction, `test` direction and `ipkg` file, e.g. https://github.com/zjhmale/sequent.idr) with this extension instead of single Idris file, this issue may probably caused by this scenario because I can reproduce you problem if I just work with a single Idris file (Internally, this extension can not find a valid working directory if you simply open a single Idris file, so it will fail to spawn an Idris backend process for all these commands).

![image](https://cloud.githubusercontent.com/assets/6234553/23913186/1aff09c8-091d-11e7-9fb1-eab5f5e54b85.png)

Hope this may help you, Cheers!

**Comment by zjhmale** [comment]
Hi @karljs, I think this issue is already perfectly addressed here,

![screenshot](https://cloud.githubusercontent.com/assets/6234553/23943449/7d123864-09aa-11e7-849f-eea89a2266fb.gif)

I will release a new version tonight and you can check it out, if you still got the same problem, pls feel free to reopen this issue, Cheers!
